// Generated by CoffeeScript 1.6.1
'use strict';
var App;

App = (function() {

  App.detailsURL = /^#employees\/(\d+)/;

  App.showAlert = function(message, title) {
    if (navigator.notification) {
      return navigator.notification.alert(message, null, title, "OK");
    } else {
      return alert((title ? "" + title + ": " + message : message));
    }
  };

  function App() {
    var _this = this;
    this.route = function() {
      var hash, match;
      hash = window.location.hash;
      if (!hash) {
        if (_this.homePage) {
          _this.slidePage(_this.homePage);
        } else {
          _this.homePage = new HomeView(_this.store).render(true);
          _this.currentPage = _this.homePage;
          $('body').append(_this.homePage.el);
        }
        return;
      }
      match = hash.match(App.detailsURL);
      if (match) {
        return _this.store.findById(Number(match[1]), function(employee) {
          return _this.slidePage(new EmployeeView(employee).render());
        });
      }
    };
    this.registerEvents = function() {
      var $body, event_begin, event_end, tappable, touchable;
      tappable = 'tappable-active';
      touchable = document.documentElement.hasOwnProperty('ontouchstart');
      event_begin = touchable ? 'touchstart' : 'mousedown';
      event_end = touchable ? 'touchend' : 'mouseup';
      $body = $('body');
      $body.on(event_begin, 'a', function(event) {
        return $(event.target).addClass(tappable);
      });
      $body.on(event_end, 'a', function(event) {
        return $(event.target).removeClass(tappable);
      });
      return $(window).on('hashchange', $.proxy(this.route, this));
    };
    this.registerEvents();
    this.slidePage = function(page) {
      var $el, direction, homepage;
      $('.page:not(.stage-center, .homePage)').remove();
      $el = $(page.el);
      homepage = page === _this.homePage;
      $el.attr('class', "page stage-" + (homepage ? 'left' : 'right')).appendTo('body');
      direction = (homepage ? 'right' : 'left');
      return setTimeout(function() {
        $(_this.currentPage.el).attr('class', "page transition stage-" + direction + (homepage ? '' : ' homePage'));
        $el.attr('class', "page stage-center transition" + (homepage ? ' homePage' : ''));
        _this.currentPage = page;
        if (homepage) {
          $('.search-key', $el).focus();
          return;
        }
        return $el.swipe({
          threshold: 0,
          swipe: function(event, direction, distance, duration, fingers) {
            if (direction === 'right') {
              return history.back();
            }
          }
        });
      });
    };
    this.store = new MemoryStore(function() {
      return _this.route();
    });
  }

  return App;

})();
