// Generated by CoffeeScript 1.6.1
'use strict';
var EmployeeView;

EmployeeView = (function() {

  EmployeeView.template = Handlebars.compile($('#employee-tpl').html());

  function EmployeeView(details) {
    this.addLocation = function(event) {
      event.preventDefault();
      navigator.geolocation.getCurrentPosition(function(position) {
        var coords;
        coords = position.coords;
        return $('.location').html("" + coords.latitude + ", " + coords.longitude);
      }, function() {
        return App.showAlert('Error getting location!');
      });
      return false;
    };
    this.addToContacts = function(event) {
      var contact;
      event.preventDefault();
      if (!navigator.contacts) {
        App.showAlert('Contacts API not supported', 'Error');
        return;
      }
      contact = navigator.contacts.create();
      contact.name = {
        givenName: details.firstName,
        familyName: details.lastName
      };
      contact.phoneNumbers = [new ContactField('work', details.officePhone, false), new ContactField('mobile', details.cellPhone, true)];
      contact.save();
      return false;
    };
    this.render = function() {
      var $el;
      $el = $('<div/>').html(EmployeeView.template(details));
      $el.on('click', '.add-location-btn', this.addLocation);
      return $el.on('click', '.add-contact-btn', this.addToContacts);
    };
  }

  return EmployeeView;

})();
