// Generated by CoffeeScript 1.6.1
'use strict';
var EmployeeView;

EmployeeView = (function() {

  EmployeeView.template = Handlebars.compile($('#employee-tpl').html());

  function EmployeeView(details) {
    this.render = function() {
      return $('<div/>').html(EmployeeView.template(details));
    };
  }

  return EmployeeView;

})();
