// Generated by CoffeeScript 1.6.1
(function() {
  var HomeView;

  HomeView = function(store) {
    this.findByName = function() {
      return store.findByName($('.search-key').val(), function(employees) {
        return $('.employee-list').html(HomeView.liTemplate(employees));
      });
    };
    this.liTemplate = Handlebars.compile($('#employee-li-tpl').html());
    this.render = function() {
      return this.el.html(HomeView.template());
    };
    this.template = Handlebars.compile($('#home-tpl').html());
    this.initialize = function() {
      return $('<div/>').on('keyup', '.search-key', this.findByName);
    };
    return this.initialize();
  };

}).call(this);
