// Generated by CoffeeScript 1.6.1
'use strict';
$(function() {
  var app, handler;
  handler = function($el, clear) {
    if (clear == null) {
      clear = false;
    }
    return null;
  };
  return app = new App(handler);
});
