// Generated by CoffeeScript 1.6.3
'use strict';
$(function() {
  var $body, $document, $wrapper, app, closeLid, minHeight, navBarHeight, on_scroll, scrollTop;
  $body = $('body');
  $document = $(document);
  $wrapper = $('#wrapper');
  navBarHeight = $('.navbar').first().height();
  scrollTop = 0;
  minHeight = 40;
  closeLid = function(e) {
    $document.scrollTop(navBarHeight);
    return e.preventDefault();
  };
  app = new App(function($el, clear) {
    if (clear == null) {
      clear = false;
    }
    return null;
  });
  on_scroll = function() {
    var stop;
    stop = $document.scrollTop();
    if (stop < navBarHeight) {
      $wrapper.click(closeLid);
      app.scroller.disable();
    } else {
      $wrapper.off();
      app.scroller.enable();
    }
    $.doTimeout('scrolling', 150, function() {
      return $document.scrollTop((navBarHeight - stop) < stop ? navBarHeight : 0);
    });
    return scrollTop = stop;
  };
  $document.on('scroll', $body, on_scroll);
  return $document.scrollTop(navBarHeight);
});
